---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "solr.fullname" . }}"

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: "{{ include "solr.fullname" . }}"
rules:
- apiGroups: [""]
  resources: [ "nodes" ]
  verbs: [ "get" ]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "solr.fullname" . }}"
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: "{{ include "solr.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: "{{ include "solr.fullname" . }}"
  apiGroup: rbac.authorization.k8s.io
